<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="sk" lang="sk">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="robots" content="{$robots}" n:ifset="$robots" />
  <title>{block #title}nette-acl{/block}</title>
  <link rel="stylesheet" href="{$basePath}/css/admin.css" type="text/css" media="screen, projection, tv" />
</head>
<body>
<div id="wrapper">

  <div id="header">
    <a id="homelink" href="{plink Default:}">nette-acl admin</a>

    <div id="userbox">
      {if isset($user)}
        <p>
          Prihlásený ako <strong>{$user->name}</strong> [{? echo implode(', ', $user->roles)}] |
          <a href="{link Default:logout}">odhlásiť</a>
        </p>
      {/if}
    </div><!-- #userbox -->
  </div><!-- #header -->

  <div id="content">
    {foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}
    {include #content}
  </div><!-- #content -->

  <div id="footer">
    <p>Copyright &copy; 2010 Nette Foundation</p>
  </div><!-- #footer -->

</div><!-- #wrapper -->
</body>
</html>
