{block #epicenter}


<h1>Folders</h1>

<a href="{plink add}">Add new folder</a>

{if count($folders) > 0}

	<table class="basic">
		<caption>Folders</caption>
		<thead>
			<tr>
				<th>Title</th>
				<th>Date Created</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>

		{foreach $folders as $folder}
		<tr>
			<td>{$folder->getTitle()}</td>
			<td>{$folder->getDateCreated()|date}</td>
			<td>
				<a href="{plink show, id => $folder->getId()}">Show files</a>
				| <a href="{plink edit, id => $folder->getId()}">Edit</a>
				| <a href="{plink remove, id => $folder->getId()}" class="confirmRemove">Remove</a>
			</td>
		</tr>
		{/foreach}

		</tbody>
	</table>

{else}
	
	<p>No folders.</p>
	
{/if}


