{**
 * Main template
 *
 * @author      Ondrej Macoszek <ondra.macoszek@gmail.com>
 * @copyright   Copyright (c) 2010 Ondrej Macoszek
 *
 * @param string   $basePath web base path
 * @param string   $robots   tell robots how to index the content of a page (optinal)
 * @param array    $flashes  flash messages
 *}
<!DOCTYPE html>
<html>
<head>


	
    <!-- General information -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="title" content="{block #title}Importium{/block}">
    <meta name="description" content="{block #description}{/block}" />
    <meta name="author" content="Coding: Ondřej Macoszek, http://ondra.macoszek.cz">

    <title>{include #title}</title>



    <!-- Main stylesheet -->
    <link rel="stylesheet" type="text/css" href="{$basePath}/ui/css/main.css" media="all" title="main theme">
    <link rel="alternate stylesheet" type="text/css" href="{$basePath}/ui/css/alternative.css" media="all" title="secondary theme">



    <!-- Javascript libraries -->
    <!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>-->
    <script src="{$basePath}/ui/lib/jquery/jquery.js" type="text/javascript"></script>
    <script src="{$basePath}/ui/lib/jquery.colorbox/jquery.colorbox-min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{$basePath}/ui/lib/jquery.colorbox/colorbox.css" media="screen" />



    <!-- Javascript settings -->
    <script type="text/javascript">
    <!--
        var baseUrl = '{!$basePath}'
        var dirUi = '{!$basePath}/ui';
    -->
    </script>
    <script src="{$basePath}/ui/js/settings.js" type="text/javascript"></script>



    <!-- Compatibility settings -->
    <!--[if IE]>
        <link rel="stylesheet" href="{$basePath}/ui/css/hacks.ie.css" type="text/css" media="all" />
    <![endif]-->



    <!-- Favicon -->
    <link rel="shortcut icon" href="{$basePath}/ui/img/misc.favicon.ico">


    
    <!-- Other -->
    <meta name="robots" content="{$robots}" n:ifset="$robots">


    
</head>
<body>

<article id="page">


	
	<header id="header" class="clf">
		<h1><a href="{plink :Front:Default:default}">Importium</a></h1>

		<nav class="main">
			<ul>
				<li><a href="{plink :Admin:User:default}">Administration</a></li>
				<li><a href="{plink :Front:Default:default}">Public</a></li>
			</ul>
		</nav>

		<section class="loggedUser" n:ifset="$loggedUser">
		{var $identityData $loggedUser->getIdentity()->getData()}
		{$identityData['realName']}
		| <a href="{plink :Admin:User:settings}">Settings</a>
		| <a href="{plink :Admin:User:logout}">Logout</a>
		</section>
	</header>

	

	<article id="body">

		<nav class="submenu clf">
			<ul>
			{if isset($loggedUser)}
				<li><a href="{plink :Admin:Folder:}">Folders</a></li>
				<li><a href="{plink :Admin:File:}">Files</a></li>
			{else}
				<li><a href="{plink :Front:Folder:}">Folders</a></li>
			{/if}
			</ul>
		</nav>

		{foreach $flashes as $flash}
			<div class="flash {$flash->type}">{$flash->message}</div>
		{/foreach}

		<section class="epicenter typotheme">
		{include #epicenter}
		</section>

	</article>



	<footer id="footer" class="clf">
		<nav>
			<ul>
				<li><a href="#page">&uarr; Jump to Top</a></li>
			</ul>
		</nav>
		<section class="backend">
			<p>Running on <a href="http://nette.org/">Nette</a> + <a href="http://www.doctrine-project.org">Doctrine</a></p>
		</section>
		<section class="credits">
			<p>Created by <a href="http://ondra.macoszek.cz">Ondra Macoszek</a></p>
		</section>
	</footer>

	

</article>

</body>
</html>
